CREATE TABLE IF NOT EXISTS characters (
    id TEXT PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'candidate',
    tier TEXT,
    ethnicity TEXT,
    background TEXT,
    age_band TEXT,
    height_cm INTEGER,
    measurements_bwh_cm TEXT,
    skin_tone TEXT,
    hair TEXT,
    eyes TEXT,
    silhouette TEXT,
    personality TEXT,
    visual_signature TEXT,
    wardrobe_anchors TEXT NOT NULL DEFAULT '[]',
    preferred_scene_tags TEXT NOT NULL DEFAULT '[]',
    signature_daily_scene_briefs TEXT NOT NULL DEFAULT '[]',
    canonical_prompt_anchor TEXT NOT NULL,
    anti_drift_rules TEXT NOT NULL DEFAULT '[]',
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS character_versions (
    id TEXT PRIMARY KEY,
    character_id TEXT NOT NULL,
    version_name TEXT NOT NULL,
    purpose TEXT NOT NULL DEFAULT 'still_default',
    checkpoint TEXT NOT NULL,
    workflow_lane TEXT NOT NULL DEFAULT 'sdxl_illustrious',
    loras TEXT NOT NULL DEFAULT '[]',
    steps INTEGER NOT NULL DEFAULT 30,
    cfg REAL NOT NULL DEFAULT 5.4,
    sampler TEXT NOT NULL DEFAULT 'euler_ancestral',
    scheduler TEXT NOT NULL DEFAULT 'normal',
    clip_skip INTEGER NOT NULL DEFAULT 2,
    width INTEGER NOT NULL DEFAULT 832,
    height INTEGER NOT NULL DEFAULT 1216,
    negative_prompt TEXT,
    prompt_prefix TEXT NOT NULL DEFAULT '',
    prompt_suffix_guidance TEXT NOT NULL DEFAULT '',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (character_id) REFERENCES characters(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_character_versions_character_purpose
    ON character_versions(character_id, purpose);

CREATE INDEX IF NOT EXISTS idx_characters_status_tier
    ON characters(status, tier, updated_at DESC);

INSERT OR IGNORE INTO characters (
    id, slug, name, status, tier, ethnicity, background, age_band,
    height_cm, measurements_bwh_cm, skin_tone, hair, eyes, silhouette,
    personality, visual_signature, wardrobe_anchors, preferred_scene_tags,
    signature_daily_scene_briefs, canonical_prompt_anchor, anti_drift_rules,
    notes, created_at, updated_at
) VALUES
(
    'char_kaede_ren',
    'kaede_ren',
    'Kaede Ren',
    'core',
    'Core A',
    'Japanese / East Asian metropolitan',
    'Tokyo-style polished city fashion persona',
    'mid-20s adult',
    168,
    '84-58-86',
    'porcelain',
    'sleek black bob',
    'cool brown',
    'slim toned',
    'composed, observant, quietly flirtatious, high self-control',
    'clean monochrome styling, poised eye contact, polished city elegance',
    '["monochrome fitted knits","satin blouse and tailored skirt","sleek mini dress and blazer","understated jewelry"]',
    '["city_night","gallery","private_booth","balcony_editorial"]',
    '["morning apartment window in a fitted knit lounge set, black bob tucked behind one ear, coffee cup in hand, minimal modern interior, soft daylight, composed intimacy","weekday cafe corner in a satin blouse and tailored skirt, laptop beside an iced drink, crossed legs, direct eye contact, polished city-girl calm","late-evening vinyl shelf moment in an oversized charcoal sweater over fitted shorts, one shoulder slightly exposed, warm lamp light, reflective apartment mood"]',
    'Kaede Ren, elegant east asian beauty, sleek black bob, cool brown eyes, porcelain skin, refined facial features, slim toned figure, high-fashion poise',
    '["no bright dyed hair","no round or cute facial styling","no oversized streetwear as main identity"]',
    'Weekly favorite core pick based on strong cross-batch performance.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'char_imani_adebayo',
    'imani_adebayo',
    'Imani Adebayo',
    'core',
    'Core A',
    'Black / Nigerian diaspora luxury editorial',
    'Global luxury editorial lead with nightlife and lifestyle range',
    'late-20s adult',
    173,
    '88-62-90',
    'deep brown',
    'soft natural curls',
    'dark',
    'statuesque editorial',
    'calm, self-possessed, warm but formidable, socially magnetic',
    'strong cheekbones, rich skin rendering, luxe presence, grounded confidence',
    '["body-skimming knits","luxe athleisure","deep jewel-tone satin","structured blazers"]',
    '["nightlife","gallery","lounge","daily_intimacy"]',
    '["early morning mirror routine in a fitted ribbed dress with a robe draped open over the shoulders, soft curls loose, skincare counter reflections, quiet luxury apartment mood","after-gym street return in luxe athleisure with a cropped jacket, gym bag over one shoulder, post-workout glow, direct eye contact, strong everyday charisma","night lounge booth in a sleek knit dress and blazer, rich dark skin catching warm lamp light, relaxed posture, intimate social power without overt glamour overload"]',
    'Imani Adebayo, striking black beauty, deep brown skin, soft natural curls, dark eyes, polished cheekbones, statuesque editorial presence',
    '["no pale skin reinterpretation","no pin-straight hair as default","avoid girlish styling"]',
    'Weekly favorite core pick with high consistency across still batches.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'char_nia_laurent',
    'nia_laurent',
    'Nia Laurent',
    'core',
    'Core A-',
    'Afro-French editorial crossover',
    'Paris nightlife and sport-luxury crossover persona',
    'late-20s adult',
    171,
    '87-61-89',
    'rich dark',
    'natural textured curls',
    'striking almond',
    'slim toned',
    'cool, stylish, poised, high social fluency',
    'sport-luxury silhouettes, polished posture, high-fashion nightlife energy',
    '["luxury sport pieces","metallic nightlife accents","tailored outerwear","black and jewel tone palette"]',
    '["motorsport","winter_avenue","red_carpet","yacht"]',
    '["morning city walk in a fitted turtleneck dress under a long coat, textured curls defined, hands in pockets, cool urban composure, luxury avenue backdrop","casual rooftop downtime in a cropped racing jacket over premium athleisure, one hand on the rail, skyline behind, sporty confidence, effortless charisma","late-evening doorway pause in a body-skimming black knit dress with metallic accessories, sharp almond-eye contact, polished corridor light, social magnetism"]',
    'Nia Laurent, afro-french editorial beauty, rich dark skin, natural textured curls, striking almond eyes, polished cheekbones, slim toned figure',
    '["avoid pastel or cute styling","keep hair texture visible","keep posture upright and polished"]',
    'Weekly favorite core pick with strong trend-pack conversion.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'char_camila_duarte',
    'camila_duarte',
    'Camila Duarte',
    'core',
    'Core A-',
    'Brazilian / Latina resort glamour',
    'Warm resort-luxury and nightlife crossover persona',
    'mid-20s adult',
    170,
    '89-60-91',
    'sun-kissed tan',
    'long chestnut waves',
    'warm hazel',
    'soft athletic',
    'open, playful, flirtatious, socially confident',
    'warm hair movement, resort polish, inviting smile, glamour-ready ease',
    '["resort dresses","satin nightlife pieces","open-neck blouses","polished beach-luxury styling"]',
    '["resort","nightlife","artist_loft","jazz_lounge"]',
    '["sunlit weekend flower market in a breezy sundress, woven tote over one shoulder, warm hazel eye contact, chestnut waves moving in the light, playful everyday charm","home balcony golden hour in an open-neck blouse and fitted shorts, bare feet, leaning on the rail, relaxed laugh, warm-weather lifestyle allure","late lounge corner in a satin blouse and denim, seated sideways on a sofa arm, one heel dangling, warm lamp pool, naturally flirtatious energy"]',
    'Camila Duarte, brazilian glamour beauty, sun-kissed tan skin, long chestnut waves, warm hazel eyes, refined facial structure, elegant proportions',
    '["no platinum or black bob redesign","avoid gothic palette as default","keep warmth and movement in hair"]',
    'Weekly favorite core pick with strong resort and lifestyle appeal.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'char_mina_sato',
    'mina_sato',
    'Mina Sato',
    'core',
    'Core B+',
    'Japanese fashion-magazine / polished city girl',
    'Accessible city-magazine beauty with clean commercial range',
    'mid-20s adult',
    166,
    '82-57-85',
    'creamy fair',
    'soft black wolf cut',
    'warm brown',
    'slim toned',
    'approachable, polished, softly charismatic, emotionally readable',
    'softly glamorous face, commercial beauty styling, warm expression',
    '["satin blouse and skirt","tailored citywear","clean magazine beauty closeups","sporty-luxury layers"]',
    '["rooftop","studio_beauty","motorsport","red_carpet"]',
    '["weekday cafe desk moment in a satin blouse and tailored skirt, warm brown eyes toward the camera, soft black wolf cut framing the face, polished social-editorial calm","after-work rooftop pause in a fitted knit top and structured mini skirt, skyline bokeh, one hand on the glass, softly charismatic smile, city-magazine beauty","weekend bookstore browse in a clean tee under a blazer with a slim skirt, one hand on a shelf, half-turn glance, approachable polished fashion energy"]',
    'Mina Sato, japanese fashion-magazine beauty, creamy fair skin, soft black wolf cut, warm brown eyes, delicate features, slim toned figure',
    '["no extreme glam contouring","no overly severe expression as default","keep soft polish over hard dominance"]',
    'Weekly favorite core pick with broad commercial usability.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
);

INSERT OR IGNORE INTO character_versions (
    id, character_id, version_name, purpose, checkpoint, workflow_lane, loras,
    steps, cfg, sampler, scheduler, clip_skip, width, height, negative_prompt,
    prompt_prefix, prompt_suffix_guidance, created_at, updated_at
) VALUES
(
    'charver_kaede_ren_still_v1',
    'char_kaede_ren',
    'still_default_v1',
    'still_default',
    'ultimateHentaiAnimeRXTRexAnime_rxV1.safetensors',
    'sdxl_illustrious',
    '[{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.34,"category":"style"},{"filename":"DetailedEyes_V3.safetensors","strength":0.41,"category":"eyes"}]',
    34, 5.5, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor clean face readability, polished city-night glamour, and sharp silhouette definition.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'charver_kaede_ren_anim_v1',
    'char_kaede_ren',
    'animation_anchor_v1',
    'animation_anchor',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Favor front or three-quarter portrait framing, simple background separation, and outfit clarity for IPAdapter animation anchors.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'charver_imani_adebayo_still_v1',
    'char_imani_adebayo',
    'still_default_v1',
    'still_default',
    'ultimateHentaiAnimeRXTRexAnime_rxV1.safetensors',
    'sdxl_illustrious',
    '[{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.34,"category":"style"},{"filename":"DetailedEyes_V3.safetensors","strength":0.41,"category":"eyes"}]',
    34, 5.5, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor rich skin rendering, clean lighting contrast, and poised social magnetism.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'charver_imani_adebayo_anim_v1',
    'char_imani_adebayo',
    'animation_anchor_v1',
    'animation_anchor',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Keep curls readable, face unobstructed, and wardrobe simple enough for motion consistency.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'charver_nia_laurent_still_v1',
    'char_nia_laurent',
    'still_default_v1',
    'still_default',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.4, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor sporty-luxury silhouettes, polished posture, and city-night energy.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'charver_nia_laurent_anim_v1',
    'char_nia_laurent',
    'animation_anchor_v1',
    'animation_anchor',
    'waiIllustriousSDXL_v160.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.48,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Keep hair texture, neck line, and shoulder silhouette clear for animation anchor use.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'charver_camila_duarte_still_v1',
    'char_camila_duarte',
    'still_default_v1',
    'still_default',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.4, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor warm movement in hair, lifestyle glamour, and inviting social energy.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'charver_camila_duarte_anim_v1',
    'char_camila_duarte',
    'animation_anchor_v1',
    'animation_anchor',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"Seet_il5-000009.safetensors","strength":0.4,"category":"style"},{"filename":"DetailedEyes_V3.safetensors","strength":0.42,"category":"eyes"}]',
    35, 5.6, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Preserve hair movement and warm skin tone, but keep backgrounds simple for motion tests.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'charver_mina_sato_still_v1',
    'char_mina_sato',
    'still_default_v1',
    'still_default',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor approachable polish, clean commercial beauty, and soft magazine-readability.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
),
(
    'charver_mina_sato_anim_v1',
    'char_mina_sato',
    'animation_anchor_v1',
    'animation_anchor',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Keep expressions soft and warm; prioritize front and three-quarter portraits for motion tests.',
    '2026-03-20T00:00:00Z',
    '2026-03-20T00:00:00Z'
);
