INSERT OR IGNORE INTO characters (
    id, slug, name, status, tier, ethnicity, background, age_band,
    height_cm, measurements_bwh_cm, skin_tone, hair, eyes, silhouette,
    personality, visual_signature, wardrobe_anchors, preferred_scene_tags,
    signature_daily_scene_briefs, canonical_prompt_anchor, anti_drift_rules,
    notes, created_at, updated_at
) VALUES
(
    'char_celeste_moretti',
    'celeste_moretti',
    'Celeste Moretti',
    'reserve',
    'Reserve A',
    'Mediterranean old-money editorial',
    'Quiet-luxury socialite beauty with strong lifestyle conversion',
    'late-20s adult',
    169,
    '86-59-88',
    'luminous ivory',
    'auburn hair',
    'green',
    'slim elegant',
    'composed, romantic, polished, subtly aloof',
    'old-money elegance, luminous skin, green-eye readability, understated confidence',
    '["oversized button-down and fitted shorts","tailored trench over a fitted mini dress","romantic sundresses","quiet-luxury knit dresses"]',
    '["quiet_luxury","flower_market","window_light","urban_after_dark"]',
    '["Sunday morning by the bed-side window in an oversized button-down over fitted shorts, one leg folded up, warm sunlight, soft intimate energy, refined apartment calm","flower market stroll in a romantic sundress with a bouquet in one arm, sunlight between awnings, graceful old-money beauty, natural favorite-bait composition","parking garage stride in a trench coat over a fitted mini dress, hard shadow lines, hand adjusting the lapel, urban after-dark confidence with quiet-luxury polish"]',
    'Celeste Moretti, mediterranean beauty, auburn hair, green eyes, luminous skin, refined facial features, slim elegant figure, old-money elegance',
    '["no neon styling as default","no platinum or jet-black hair redesign","keep elegance understated rather than overtly flashy"]',
    'Reserve promotion candidate. 15 favorites in the last 7 days with strong quiet-luxury and daily-intimacy conversion.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'char_mireya_solis',
    'mireya_solis',
    'Mireya Solis',
    'reserve',
    'Reserve A',
    'Bronzed Latina lifestyle glamour',
    'Warm modern-glamour lead with strong everyday desirability',
    'mid-20s adult',
    170,
    '88-60-90',
    'bronzed tan',
    'chestnut waves',
    'honey-brown',
    'soft athletic',
    'confident, warm, playful, socially magnetic',
    'sculpted cheekbones, chestnut hair movement, polished modern glamour, warm charisma',
    '["open-neck blouses","fitted mini dresses","tailored shorts and shirts","sleek lounge knits"]',
    '["daily_allure","street_lifestyle","window_light","night_out"]',
    '["Sunday morning by the bed-side window in an oversized button-down over fitted shorts, bronzed skin catching warm sunlight, soft intimate energy, polished apartment calm","flower market stroll in a light sundress and sandals, bouquet in one arm, honey-brown eye contact, lively street warmth, natural everyday glamour","late-night fridge light moment in a fitted tank and lounge shorts, one hand on the fridge door, cinematic apartment glow, playful but composed intimacy"]',
    'Mireya Solis, bronzed latina beauty, chestnut waves, honey-brown eyes, sculpted cheekbones, polished modern glamour, soft athletic figure',
    '["no cool gothic palette as default","keep warmth in skin and hair rendering","avoid severe or icy expression styling"]',
    'Reserve promotion candidate. 14 favorites in the last 7 days with especially strong freeform lifestyle scenes.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'char_freya_lindholm',
    'freya_lindholm',
    'Freya Lindholm',
    'reserve',
    'Reserve A-',
    'Nordic luxury fashion editorial',
    'High-status runway and resort-glamour candidate with strong luxury image fit',
    'late-20s adult',
    171,
    '86-58-88',
    'cool fair',
    'platinum blonde hair',
    'blue-gray',
    'slim toned',
    'cool, composed, exacting, high-status',
    'platinum contrast, clean jawline, icy elegance, couture posture',
    '["sculpted black gowns","deep emerald satin dresses","tailored power dresses","silk off-shoulder eveningwear"]',
    '["runway_afterglow","resort_glamour","midnight_lobby","private_jet"]',
    '["midnight hotel lobby in a sleek black column dress, glossy floor reflections, dramatic overhead lights, poised stance, polished cinematic glamour","rooftop pool at dusk in a deep emerald satin dress, city reflections on the water, elegant seated pose, cool luxury confidence","intimate piano bar in a silk off-shoulder evening dress, amber lighting, one hand resting near the glass, composed high-status allure"]',
    'Freya Lindholm, nordic luxury beauty, cool fair skin, platinum blonde hair, blue-gray eyes, refined jawline, elegant proportions, slim toned figure',
    '["no warm bronze skin shift","avoid cute or bubbly styling","keep platinum hair clean and expensive rather than messy"]',
    'Reserve promotion candidate. 10 favorites in the last 7 days with consistent conversion in luxury editorial scenes.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'char_lucia_moreau',
    'lucia_moreau',
    'Lucia Moreau',
    'reserve',
    'Reserve A-',
    'Mediterranean film-star glamour',
    'Classic cinema beauty candidate with strong nightlife and piano-lounge fit',
    'late-20s adult',
    170,
    '87-59-89',
    'sunlit ivory',
    'glossy chestnut hair',
    'expressive green',
    'slim toned',
    'glamorous, emotionally vivid, poised, cinematic',
    'film-star face, glossy chestnut hair, green-eye expression, classic after-dark elegance',
    '["silk off-shoulder evening dresses","deep emerald satin","black column dresses","tailored scarlet dresses"]',
    '["piano_bar","midnight_lobby","seaside_lounge","runway_afterglow"]',
    '["intimate piano bar in a silk off-shoulder evening dress, amber lights, seated beside a grand piano, expressive green eyes toward the camera, classic nightlife glamour","marble hotel lobby at midnight in a sleek black column dress, glossy reflections, composed film-star posture, refined cinematic styling","seaside lounge at blue hour in a deep emerald satin dress, ocean breeze in the chestnut hair, one hand on the chair arm, elegant resort after-dark mood"]',
    'Lucia Moreau, mediterranean film-star beauty, sunlit ivory skin, glossy chestnut hair, expressive green eyes, refined features, elegant proportions, slim toned figure',
    '["no sporty-streetwear as default","avoid overly cute facial styling","keep glamour classic rather than trendy or noisy"]',
    'Reserve promotion candidate. 10 favorites in the last 7 days with notable strength in nightlife glamour scenes.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'char_hana_seo',
    'hana_seo',
    'Hana Seo',
    'reserve',
    'Reserve B+',
    'Korean luxury beauty editorial',
    'Precision-clean luxury candidate with strong palace, lounge, and spa corridor conversion',
    'mid-20s adult',
    167,
    '84-58-86',
    'porcelain',
    'sleek obsidian bob haircut',
    'amber-brown',
    'slim toned',
    'precise, controlled, sophisticated, quietly seductive',
    'obsidian bob, precise jawline, polished symmetry, luxury calm',
    '["monochrome dresses","camel wool coats","emerald satin eveningwear","atelier tailoring"]',
    '["winter_palace","piano_lounge","spa_corridor","observatory_terrace"]',
    '["winter palace corridor in a camel wool coat over a monochrome dress, cold window light, elegant walking pose, quiet sophisticated calm","head-and-shoulders piano lounge portrait in a silk off-shoulder evening dress, amber lights, magnetic stare, premium nightlife polish","observatory terrace at night in a deep emerald satin dress, city glow below, elegant seated pose, cinematic twilight color and restrained sensuality"]',
    'Hana Seo, korean luxury beauty, porcelain skin, sleek obsidian bob haircut, amber-brown eyes, elegant jawline, refined features, slim toned figure',
    '["no bright dyed hair","avoid overtly cute styling","keep silhouette precise and polished"]',
    'Reserve development candidate. 9 favorites in the last 7 days with strong symmetry-driven editorial conversion.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'char_elena_petrov',
    'elena_petrov',
    'Elena Petrov',
    'reserve',
    'Reserve B+',
    'Eastern European couture editorial',
    'Couture and winter-luxury candidate with balanced nightlife range',
    'late-20s adult',
    172,
    '87-60-89',
    'luminous fair',
    'long ash-brown hair',
    'steel-blue',
    'slim toned',
    'cool, aristocratic, composed, exacting',
    'steel-blue gaze, ash-brown length, couture bearing, aristocratic calm',
    '["draped couture gowns","camel wool outerwear","emerald satin dresses","silk eveningwear"]',
    '["couture_fitting_room","winter_palace","piano_lounge","observatory_terrace"]',
    '["couture fitting room in a draped gown in progress, mirrors and pins behind her, poised standing pose, elevated atelier glamour","winter palace corridor in a camel wool coat over a monochrome dress, long ash-brown hair catching cold light, elegant walking pose, disciplined sophistication","observatory terrace at night in a deep emerald satin dress, city glow below, composed seated pose, premium twilight editorial with restrained magnetism"]',
    'Elena Petrov, eastern european couture beauty, luminous fair skin, long ash-brown hair, steel-blue eyes, refined facial structure, elegant proportions, slim toned figure',
    '["no bubblegum or cute styling","avoid heavy streetwear identity","keep mood cool, elegant, and couture-first"]',
    'Reserve development candidate. 9 favorites in the last 7 days with especially stable couture and winter-luxury scenes.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'char_keira_okafor',
    'keira_okafor',
    'Keira Okafor',
    'reserve',
    'Reserve B',
    'Afro-British fashion nightlife editorial',
    'Nightlife-forward fashion candidate with strong couture and observatory scenes',
    'late-20s adult',
    172,
    '88-61-90',
    'rich dark',
    'sleek natural curls',
    'striking almond',
    'slim toned',
    'bold, fashion-forward, self-assured, magnetic',
    'sleek curls, rich skin rendering, almond-eye intensity, elevated nightlife glamour',
    '["formal black gowns","silver mini blazer dresses","sleek leather trench layers","couture salon dresses"]',
    '["observatory_night","couture_salon","backstage_mirror","nightlife_exit"]',
    '["observatory terrace at night in a jet-black formal gown, distant city glow, elegant standing pose, refined starlit sensuality","couture fitting salon in a draped gown with mirrors and pins, poised standing posture, high-fashion atelier intimacy, strong eye contact","limousine afterparty exit in a tailored silver mini blazer dress, flash photography, one-foot-out pose, polished celebrity energy without overt excess"]',
    'Keira Okafor, afro-british fashion beauty, rich dark skin, sleek natural curls, striking almond eyes, polished cheekbones, elegant proportions, slim toned figure',
    '["no pale-skin reinterpretation","keep curls sleek rather than pin-straight","avoid girlish styling and keep nightlife polish mature"]',
    'Reserve development candidate. 8 favorites in the last 7 days with concentrated nightlife-fashion wins.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
);

INSERT OR IGNORE INTO character_versions (
    id, character_id, version_name, purpose, checkpoint, workflow_lane, loras,
    steps, cfg, sampler, scheduler, clip_skip, width, height, negative_prompt,
    prompt_prefix, prompt_suffix_guidance, created_at, updated_at
) VALUES
(
    'charver_celeste_moretti_still_v1',
    'char_celeste_moretti',
    'still_default_v1',
    'still_default',
    'ultimateHentaiAnimeRXTRexAnime_rxV1.safetensors',
    'sdxl_illustrious',
    '[{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.34,"category":"style"},{"filename":"DetailedEyes_V3.safetensors","strength":0.41,"category":"eyes"}]',
    34, 5.5, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor graceful old-money styling, clean green-eye readability, and cinematic quiet-luxury framing.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_celeste_moretti_anim_v1',
    'char_celeste_moretti',
    'animation_anchor_v1',
    'animation_anchor',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Favor tidy hair silhouette, front or three-quarter portrait framing, and quiet-luxury outfit clarity for animation anchors.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_mireya_solis_still_v1',
    'char_mireya_solis',
    'still_default_v1',
    'still_default',
    'ultimateHentaiAnimeRXTRexAnime_rxV1.safetensors',
    'sdxl_illustrious',
    '[{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.34,"category":"style"},{"filename":"DetailedEyes_V3.safetensors","strength":0.41,"category":"eyes"}]',
    34, 5.5, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor warm skin rendering, chestnut hair movement, and polished modern lifestyle glamour.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_mireya_solis_anim_v1',
    'char_mireya_solis',
    'animation_anchor_v1',
    'animation_anchor',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Favor simple wardrobe separation, clean cheekbone readability, and warm natural-light portrait framing.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_freya_lindholm_still_v1',
    'char_freya_lindholm',
    'still_default_v1',
    'still_default',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor clean platinum contrast, premium couture posture, and cool luxury finish.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_freya_lindholm_anim_v1',
    'char_freya_lindholm',
    'animation_anchor_v1',
    'animation_anchor',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Favor tidy platinum hair, low-noise backgrounds, and front or three-quarter portrait stability.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_lucia_moreau_still_v1',
    'char_lucia_moreau',
    'still_default_v1',
    'still_default',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor expressive green-eye contact, glossy chestnut hair, and classic after-dark glamour.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_lucia_moreau_anim_v1',
    'char_lucia_moreau',
    'animation_anchor_v1',
    'animation_anchor',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Favor chestnut hair readability, face-forward framing, and outfit simplicity for motion consistency.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_hana_seo_still_v1',
    'char_hana_seo',
    'still_default_v1',
    'still_default',
    'waiIllustriousSDXL_v160.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor precise symmetry, polished obsidian-bob silhouette, and restrained luxury calm.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_hana_seo_anim_v1',
    'char_hana_seo',
    'animation_anchor_v1',
    'animation_anchor',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Favor precise bob edges, uncluttered portrait framing, and monochrome wardrobe clarity.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_elena_petrov_still_v1',
    'char_elena_petrov',
    'still_default_v1',
    'still_default',
    'waiIllustriousSDXL_v160.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor steel-blue gaze clarity, couture posture, and cool-luxury tonal control.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_elena_petrov_anim_v1',
    'char_elena_petrov',
    'animation_anchor_v1',
    'animation_anchor',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Favor face-forward couture portraits, hair separation from background, and cool neutral outfit anchors.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_keira_okafor_still_v1',
    'char_keira_okafor',
    'still_default_v1',
    'still_default',
    'waiIllustriousSDXL_v160.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, high-response beauty editorial, fully clothed, tasteful adult allure, strong eye contact, luminous skin',
    'Favor rich dark-skin rendering, sleek curls, and elevated nightlife-fashion finish.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
),
(
    'charver_keira_okafor_anim_v1',
    'char_keira_okafor',
    'animation_anchor_v1',
    'animation_anchor',
    'waiIllustriousSDXL_v160.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.45,"category":"eyes"},{"filename":"Face_Enhancer_Illustrious.safetensors","strength":0.36,"category":"style"}]',
    31, 5.35, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, refined facial features, clean silhouette, identity-preserving portrait',
    'Favor clean curl silhouette, high cheekbone readability, and simple formalwear for animation lock.',
    '2026-03-21T00:00:00Z',
    '2026-03-21T00:00:00Z'
);
