INSERT INTO character_versions (
    id, character_id, version_name, purpose, checkpoint, workflow_lane, loras,
    steps, cfg, sampler, scheduler, clip_skip, width, height, negative_prompt,
    prompt_prefix, prompt_suffix_guidance, created_at, updated_at
) VALUES
(
    'charver_kaede_ren_canonical_natural_v1',
    'char_kaede_ren',
    'canonical_natural_v1',
    'canonical_natural',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.22,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor believable posture, understated expression, and ordinary-life realism over glossy glamour.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_imani_adebayo_canonical_natural_v1',
    'char_imani_adebayo',
    'canonical_natural_v1',
    'canonical_natural',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.22,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor rich skin texture, calm warmth, and natural curls without over-polishing the face.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_nia_laurent_canonical_natural_v1',
    'char_nia_laurent',
    'canonical_natural_v1',
    'canonical_natural',
    'waiIllustriousSDXL_v160.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.24,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor quiet confidence, textured hair readability, and natural movement over nightlife gloss.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_camila_duarte_canonical_natural_v1',
    'char_camila_duarte',
    'canonical_natural_v1',
    'canonical_natural',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"Seet_il5-000009.safetensors","strength":0.12,"category":"style"},{"filename":"DetailedEyes_V3.safetensors","strength":0.18,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor warm daylight, gentle hair movement, and easygoing charm instead of overt glamour posing.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_mina_sato_canonical_natural_v1',
    'char_mina_sato',
    'canonical_natural_v1',
    'canonical_natural',
    'prefectIllustriousXL_v70.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.22,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor approachable softness, casual magazine-natural polish, and warm emotional readability.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_celeste_moretti_canonical_natural_v1',
    'char_celeste_moretti',
    'canonical_natural_v1',
    'canonical_natural',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.22,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor quiet elegance, natural window light, and understated luxury without glossy perfection.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_mireya_solis_canonical_natural_v1',
    'char_mireya_solis',
    'canonical_natural_v1',
    'canonical_natural',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.22,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor sun-warm skin, unforced posture, and everyday apartment or street realism over glossy allure.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_freya_lindholm_canonical_natural_v1',
    'char_freya_lindholm',
    'canonical_natural_v1',
    'canonical_natural',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.22,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor crisp natural light, believable clothing texture, and calm restraint over glossy couture intensity.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_lucia_moreau_canonical_natural_v1',
    'char_lucia_moreau',
    'canonical_natural_v1',
    'canonical_natural',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.22,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor classic softness, expressive eyes, and grounded room light instead of staged after-dark glamour.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_hana_seo_canonical_natural_v1',
    'char_hana_seo',
    'canonical_natural_v1',
    'canonical_natural',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.22,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor precise bob readability, unforced symmetry, and quiet daily realism without sterile perfection.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_elena_petrov_canonical_natural_v1',
    'char_elena_petrov',
    'canonical_natural_v1',
    'canonical_natural',
    'waiIllustriousSDXL_v140.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.22,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor cool natural light, believable hair fall, and graceful realism over couture stiffness.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
),
(
    'charver_keira_okafor_canonical_natural_v1',
    'char_keira_okafor',
    'canonical_natural_v1',
    'canonical_natural',
    'waiIllustriousSDXL_v160.safetensors',
    'sdxl_illustrious',
    '[{"filename":"DetailedEyes_V3.safetensors","strength":0.24,"category":"eyes"}]',
    30, 5.0, 'euler_ancestral', 'normal', 2, 832, 1216,
    'child, teen, underage, school uniform, text, logo, watermark, blurry, lowres, deformed, bad anatomy, extra fingers, duplicate, poorly drawn hands, plastic skin, hyper-glossy skin, doll-like eyes, over-sharpened details, exaggerated makeup, stiff pose, explicit nudity, graphic sexual content',
    'masterpiece, best quality, original character, adult woman, solo, fully clothed, natural beauty illustration, relaxed expression, subtle skin texture, soft ambient light, delicate linework, painterly shading, lived-in atmosphere',
    'Favor mature calm, clean curl silhouette, and natural room light over nightlife shine.',
    '2026-03-22T00:00:00Z',
    '2026-03-22T00:00:00Z'
)
ON CONFLICT(character_id, purpose) DO UPDATE SET
    id = excluded.id,
    version_name = excluded.version_name,
    checkpoint = excluded.checkpoint,
    workflow_lane = excluded.workflow_lane,
    loras = excluded.loras,
    steps = excluded.steps,
    cfg = excluded.cfg,
    sampler = excluded.sampler,
    scheduler = excluded.scheduler,
    clip_skip = excluded.clip_skip,
    width = excluded.width,
    height = excluded.height,
    negative_prompt = excluded.negative_prompt,
    prompt_prefix = excluded.prompt_prefix,
    prompt_suffix_guidance = excluded.prompt_suffix_guidance,
    updated_at = excluded.updated_at;
